name: Validate HACS

on:
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
